name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - black
  - flake8
  - ipycanvas
  - matplotlib
  - nbqa
  - numpy
  - pandas
  - python
  - simpy
  - sim-tools
  - xeus-python
