name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - ipycanvas
  - matplotlib
  - numpy
  - pandas
  - python=3.11
  - simpy
  - sim-tools
  - xeus-python
